# name: Deploy til PROD (prod-gpc)

# on:
#   release:
#     types: [released]

# jobs:
#   deploy-to-prod:
#     name: Deploy to prod-gcp
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: nais/deploy/actions/deploy@master
#         env:
#           TEAM: helsearbeidsgiver
#           APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#           CLUSTER: prod-gcp
#           RESOURCE: deploy/prod.yaml
#           REF: ${{ env.COMMIT }}
#           IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}:latest
